spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
#配置调用product-service服务采用的负载均衡策略 随机
PRODUCT-SERVICE:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
#回退机制或者兜底数据
feign:
  hystrix:
    enabled: true
#对外开放健康状态
management:
  endpoints:
    web:
      exposure:
        include: '*'
#熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
circuitBreaker:
  enabled: true
  requestVolumeThreshold: 5 #触发熔断的最小请求次数，默认20
  errorThresholdPercentage: 10 #触发熔断的失败请求最小占比，默认50%
  sleepWindowInMilliseconds: 30000 #熔断多少秒后去尝试请求，默认是5S
